

<!-- adcom tag ***** lb_pokekaru clicked [Unsecure] *****-->
<img src="http://leadback.advertising.com/adcedge/lb?site=733844&betr=lb_pokekaru=1[2160]" width="1" height="1" border="0">
<!-- end/adcom tag -->

<!-- rttag YDN 20130507 START -->
<script type="text/javascript" language="javascript">
var yahoo_retargeting_id = 'listing1930';
var yahoo_retargeting_label = '';
</script>
<script type="text/javascript" language="javascript" src="//b92.yahoo.co.jp/js/s_retargeting.js"></script>
<!-- rttag YDN 20130507 END -->

<?php
if($_SERVER['SERVER_PORT'] == 443){
/************************************************************************/
/* HTTPSページ用タグ表示                                                 */
/************************************************************************/
/* HTTPS_PAGEの間に記述してください。 */
print <<< HTTPS_PAGE

<!-- TAGGYタグ -->
<script type="text/javascript" src="https://e01.taggyad.jp/js/entry.js"></script>
<script type="text/javascript" src="https://e01.taggyad.jp/js/ext/poke.js"></script>
<!-- /TAGGYタグ -->

HTTPS_PAGE;
}else{
/************************************************************************/
/* HTTPページ用タグ表示                                                  */
/************************************************************************/
/* HTTP_PAGEの間に記述してください。 */
print <<< HTTP_PAGE

<!-- for pixel tracking -->
<img src="http://m.one.impact-ad.jp/pix?p=19575&t=i"/>

<!-- TAGGYタグ -->
<script type="text/javascript" src="http://e01.taggyad.jp/js/entry.js"></script>
<script type="text/javascript" src="http://e01.taggyad.jp/js/ext/poke.js"></script>
<!-- /TAGGYタグ -->

HTTP_PAGE;
}
if(!ereg("end\.php", $_SERVER["REQUEST_URI"])){
/************************************************************************/
/* 申込完了(サンクス)ページ以外用タグ表示                                  */
/************************************************************************/
/* NOTEND_PAGEの間に記述してください。 */
print <<< NOTEND_PAGE

<!-- フリーセルリマケ用タグ 2013.10.21 -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 979400865;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/979400865/?value=0&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<!-- /フリーセルリマケ用タグ 2013.10.21 -->

<!-- BLADE 計測タグ -->
<script type="text/javascript" class="microad_blade_track">
<!--
var microad_blade_jp = microad_blade_jp || { 'params' : new Array(), 'complete_map' : new Object() };
(function() {
var param = {'co_account_id' : '6959', 'group_id' : '', 'country_id' : '1', 'ver' : '2.1.0'};
microad_blade_jp.params.push(param);

var src = (location.protocol == 'https:')
? 'https://d-track.send.microad.jp/js/blade_track_jp.js' : 'http://d-cache.microad.jp/js/blade_track_jp.js';

var bs = document.createElement('script');
bs.type = 'text/javascript'; bs.async = true;
bs.charset = 'utf-8'; bs.src = src;

var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(bs, s);
})();
-->
</script>
<!-- /BLADE 計測タグ -->

NOTEND_PAGE;
}else{
/************************************************************************/
/* 申込完了(サンクス)ページ用タグ表示                                  */
/************************************************************************/
/* END_PAGEの間に記述してください。 */
print <<< END_PAGE

<!-- YahooリスティングCVタグ 20150127 -->
<!-- Yahoo Code for your Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var yahoo_conversion_id = 1000178378;
var yahoo_conversion_label = "QkoDCOuNmVkQu-6KyAM";
var yahoo_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="https://s.yimg.jp/images/listing/tool/cv/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="https://b91.yahoo.co.jp/pagead/conversion/1000178378/?value=0&amp;label=QkoDCOuNmVkQu-6KyAM&amp;guid=ON&amp;script=0&amp;disvt=true"/>
</div>
</noscript>
<!-- /YahooリスティングCVタグ 20150127 -->

<!-- GoogleリスティングCVタグ 20150127 -->
<!-- Google Code for PC_CV&#12479;&#12464; Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 953475869;
var google_conversion_language = "ja";
var google_conversion_format = "2";
var google_conversion_color = "ffffff";
var google_conversion_label = "o7b9CPuOmVkQncbTxgM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/953475869/?label=o7b9CPuOmVkQncbTxgM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<!-- /GoogleリスティングCVタグ 20150127 -->

<!-- YDN CVタグ　20150127 -->
<script type="text/javascript" language="javascript">
  /* <![CDATA[ */
  var yahoo_ydn_conv_io = "nlRxecoOLDWgx0Fsg8VC";
  var yahoo_ydn_conv_label = "OKNZWMLG4ZCMRFC73TM822392";
  var yahoo_ydn_conv_transaction_id = "";
  var yahoo_ydn_conv_amount = "0";
  /* ]]> */
</script>
<script type="text/javascript" language="javascript" charset="UTF-8" src="//b90.yahoo.co.jp/conv.js"></script>
<!-- YDN CVタグ　20150127 -->

<!-- BLADE CVタグ -->
<script type="text/javascript" class="microad_blade_track">
<!--
var microad_blade_jp = microad_blade_jp || { 'params' : new Array(), 'complete_map' : new Object() };
(function() {
var param = {'co_account_id' : '6959', 'group_id' : 'convtrack19972', 'country_id' : '1', 'ver' : '2.1.0'};
microad_blade_jp.params.push(param);

var src = (location.protocol == 'https:')
? 'https://d-track.send.microad.jp/js/blade_track_jp.js' : 'http://d-cache.microad.jp/js/blade_track_jp.js';

var bs = document.createElement('script');
bs.type = 'text/javascript'; bs.async = true;
bs.charset = 'utf-8'; bs.src = src;

var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(bs, s);
})();
-->
</script>
<!-- /BLADE CVタグ -->

<!-- BLADE ディスプレイ広告 CVタグ -->
<!-- Google Code for &#30003;&#12375;&#36796;&#12415; Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 976836089;
var google_conversion_language = "en";
var google_conversion_format = "2";
var google_conversion_color = "ffffff";
var google_conversion_label = "MtBiCJ_tzxoQ-avl0QM";
var google_conversion_value = 0;
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/976836089/?value=0&amp;label=MtBiCJ_tzxoQ-avl0QM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<!-- /BLADE ディスプレイ広告 CVタグ -->

END_PAGE;
}
?>

<!-- ClickTale Bottom part -->

<script type='text/javascript'>
// The ClickTale Balkan Tracking Code may be programmatically customized using hooks:
// 
//   function ClickTalePreRecordingHook() { /* place your customized code here */  }
//
// For details about ClickTale hooks, please consult the wiki page http://wiki.clicktale.com/Article/Customizing_code_version_2

document.write(unescape("%3Cscript%20src='"+
(document.location.protocol=='https:'?
"https://clicktalecdn.sslcs.cdngc.net/www14/ptc/532127ec-12c3-4ebd-bae3-cd331079d102.js":
"http://cdn.clicktale.net/www14/ptc/532127ec-12c3-4ebd-bae3-cd331079d102.js")+"'%20type='text/javascript'%3E%3C/script%3E"));
</script>

<!-- ClickTale end of Bottom part -->

<!--  YiCHA 共通タグ　20150302 -->
<script type="text/javascript">
var _mvq = window._mvq || [];window._mvq = _mvq;
_mvq.push(['$setAccount', 'm-127182-0']);

_mvq.push(['$logConversion']);
(function() {
	var mvl = document.createElement('script');
	mvl.type = 'text/javascript'; mvl.async = true;
	mvl.src = ('https:' == document.location.protocol ? 'https://static-ssl.mediav.com/mvl.js' : 'http://static.mediav.com/mvl.js');
	var s = document.getElementsByTagName('script')[0];
	s.parentNode.insertBefore(mvl, s); 
})();	

</script>
<!--  end/YiCHA 共通タグ　20150302 -->

